basic:
    name: minnesota.teach.org
    environments:
        production: 'https://minnesota.teach.org'
        staging: 'https://minnesota.staging-5em2ouy-tsy4np5h7paxs.us-2.platformsh.site'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /about
        - /support
        - /media
        - '/?modalType=signUp'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 5
    night_mode: ''
    retina_images: ''
    performance:
        workers_production: '21'
        workers_nonproduction: '7'
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: single-site
